#
# Module manifest for module 'PSGet_LatestUpdate'
#
# Generated by: Aaron Parker
#
# Generated on: 8/3/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'LatestUpdate.psm1'

# Version number of this module.
ModuleVersion = '3.0.164'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '1a3f9720-247a-4a25-8120-a164b35856ef'

# Author of this module
Author = 'Aaron Parker'

# Company or vendor of this module
CompanyName = 'stealthpuppy'

# Copyright statement for this module
Copyright = '(c) 2019 stealthpuppy. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A module for retrieving the latest Windows 10 / Windows Server 2016, 2019, Semi Annual Channel Cumulative Updates, Servicing Stack Updates, .NET Framework Cumulative Updates,  Monthly Rollups for 8.1 / 7 (and Windows Server 2012 R2, 2008 R2), the latest Adobe Flash Player updates and Windows Defender antimalware platform updates from the Microsoft Update History feeds. In addition, the module provides a function for downloading the update files locally.

This module assists IT Pros in speeding Windows operating system deployments with tracking of Windows updates, offline patching in MDT for reference images or PC deployments, or direct application of updates to a WIM.

PowerShell Core is full suppported.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-LatestAdobeFlashUpdate', 'Get-LatestCumulativeUpdate', 
               'Get-LatestMonthlyRollup', 'Get-LatestNetFrameworkUpdate', 
               'Get-LatestServicingStackUpdate', 'Get-LatestWindowsDefenderUpdate', 
               'Save-LatestUpdate')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-LatestUpdate', 'Get-LatestFlash', 'Get-LatestServicingStack'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    #RepositorySourceLocation of this module
    RepositorySourceLocation = 'https://github.com/aaronparker/LatestUpdate/'

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Windows10','WindowsServer2019','WindowsServer2016','CumulativeUpdate','AdobeFlash','Adobe','Flash','LatestUpdate','MDT','MicrosoftDeploymentToolkit','MonthlyUpdate','ServicingStack','WindowsDefender'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/aaronparker/LatestUpdate/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/aaronparker/LatestUpdate/'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/aaronparker/LatestUpdate/master/img/download.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'https://docs.stealthpuppy.com/docs/latestupdate/change-log'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

